### ISSUE TITLE
Hi,sir,could you help me with two questions?

### ISSUE THREAD

**Issue by yangqincheng** [wencolani/CrossE#1]
What configuration are you using?
 What is the approximate running time?
Thank you for your attention
Looking forward to your reply~

**Comment by wencolani** [comment]
Hi, the detailed configuration please refer to 5.1.2 Implementation Details in the original paper [https://dl.acm.org/citation.cfm?id=3291014]. 
For the running time, I can't remember the exact time cost.  It should be about a few hours running with one GPU.

**Comment by yangqincheng** [comment]
> Hi, the detailed configuration please refer to 5.1.2 Implementation Details in the original paper [https://dl.acm.org/citation.cfm?id=3291014].
> For the running time, I can't remember the exact time cost. It should be about a few hours running with one GPU.

Thank you for your reply~It's very helpful for me.
